// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job.sql

package db

import (
	"context"
	"database/sql"
)

const claimJob = `-- name: ClaimJob :execrows
UPDATE jobs
SET next_run_at = ?1,
	last_run_at = ?2,
	last_status = 'running'
WHERE id = ?3
	AND enabled = 1
	AND next_run_at = ?4
`

type ClaimJobParams struct {
	NewNextRunAt      sql.NullTime
	LastRunAt         sql.NullTime
	ID                int64
	ExpectedNextRunAt sql.NullTime
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimJob,
		arg.NewNextRunAt,
		arg.LastRunAt,
		arg.ID,
		arg.ExpectedNextRunAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (user_id, session_id, schedule, prompt, enabled, next_run_at, provider_id, model)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, session_id, schedule, prompt, enabled, last_run_at, last_status, next_run_at, created_at, updated_at, provider_id, model
`

type CreateJobParams struct {
	UserID     int64
	SessionID  sql.NullInt64
	Schedule   string
	Prompt     string
	Enabled    int64
	NextRunAt  sql.NullTime
	ProviderID sql.NullInt64
	Model      string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.UserID,
		arg.SessionID,
		arg.Schedule,
		arg.Prompt,
		arg.Enabled,
		arg.NextRunAt,
		arg.ProviderID,
		arg.Model,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Schedule,
		&i.Prompt,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.Model,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, user_id, session_id, schedule, prompt, enabled, last_run_at, last_status, next_run_at, created_at, updated_at, provider_id, model
FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Schedule,
		&i.Prompt,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.Model,
	)
	return i, err
}

const listDueJobs = `-- name: ListDueJobs :many
SELECT id, user_id, session_id, schedule, prompt, enabled, last_run_at, last_status, next_run_at, created_at, updated_at, provider_id, model
FROM jobs
WHERE enabled = 1 AND next_run_at IS NOT NULL AND next_run_at <= ?
ORDER BY next_run_at, id
`

func (q *Queries) ListDueJobs(ctx context.Context, nextRunAt sql.NullTime) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listDueJobs, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Schedule,
			&i.Prompt,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByUser = `-- name: ListJobsByUser :many
SELECT id, user_id, session_id, schedule, prompt, enabled, last_run_at, last_status, next_run_at, created_at, updated_at, provider_id, model
FROM jobs
WHERE user_id = ?
ORDER BY id
`

func (q *Queries) ListJobsByUser(ctx context.Context, userID int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Schedule,
			&i.Prompt,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJobSession = `-- name: SetJobSession :exec
UPDATE jobs
SET session_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetJobSessionParams struct {
	SessionID sql.NullInt64
	ID        int64
}

func (q *Queries) SetJobSession(ctx context.Context, arg SetJobSessionParams) error {
	_, err := q.db.ExecContext(ctx, setJobSession, arg.SessionID, arg.ID)
	return err
}

const setJobStatus = `-- name: SetJobStatus :exec
UPDATE jobs
SET last_status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetJobStatusParams struct {
	LastStatus string
	ID         int64
}

func (q *Queries) SetJobStatus(ctx context.Context, arg SetJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, setJobStatus, arg.LastStatus, arg.ID)
	return err
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET schedule = ?, prompt = ?, enabled = ?, next_run_at = ?, provider_id = ?, model = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, user_id, session_id, schedule, prompt, enabled, last_run_at, last_status, next_run_at, created_at, updated_at, provider_id, model
`

type UpdateJobParams struct {
	Schedule   string
	Prompt     string
	Enabled    int64
	NextRunAt  sql.NullTime
	ProviderID sql.NullInt64
	Model      string
	ID         int64
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.Schedule,
		arg.Prompt,
		arg.Enabled,
		arg.NextRunAt,
		arg.ProviderID,
		arg.Model,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Schedule,
		&i.Prompt,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.Model,
	)
	return i, err
}
