// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_provider.sql

package db

import (
	"context"
)

const clearDefaultLLMProviders = `-- name: ClearDefaultLLMProviders :exec
UPDATE llm_providers
SET is_default = 0
WHERE user_id = ? AND is_default = 1
`

func (q *Queries) ClearDefaultLLMProviders(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, clearDefaultLLMProviders, userID)
	return err
}

const createLLMProvider = `-- name: CreateLLMProvider :one
INSERT INTO llm_providers (user_id, name, provider, base_url, api_key, is_default)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, provider, base_url, api_key, is_default, created_at, updated_at
`

type CreateLLMProviderParams struct {
	UserID    int64
	Name      string
	Provider  string
	BaseUrl   string
	ApiKey    string
	IsDefault int64
}

func (q *Queries) CreateLLMProvider(ctx context.Context, arg CreateLLMProviderParams) (LlmProvider, error) {
	row := q.db.QueryRowContext(ctx, createLLMProvider,
		arg.UserID,
		arg.Name,
		arg.Provider,
		arg.BaseUrl,
		arg.ApiKey,
		arg.IsDefault,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLLMModelsByProvider = `-- name: DeleteLLMModelsByProvider :exec
DELETE FROM llm_models
WHERE provider_id = ?
`

func (q *Queries) DeleteLLMModelsByProvider(ctx context.Context, providerID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLLMModelsByProvider, providerID)
	return err
}

const deleteLLMProvider = `-- name: DeleteLLMProvider :exec
DELETE FROM llm_providers
WHERE id = ?
`

func (q *Queries) DeleteLLMProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLLMProvider, id)
	return err
}

const getDefaultLLMProvider = `-- name: GetDefaultLLMProvider :one
SELECT id, user_id, name, provider, base_url, api_key, is_default, created_at, updated_at
FROM llm_providers
WHERE user_id = ? AND is_default = 1
`

func (q *Queries) GetDefaultLLMProvider(ctx context.Context, userID int64) (LlmProvider, error) {
	row := q.db.QueryRowContext(ctx, getDefaultLLMProvider, userID)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLLMProvider = `-- name: GetLLMProvider :one
SELECT id, user_id, name, provider, base_url, api_key, is_default, created_at, updated_at
FROM llm_providers
WHERE id = ?
`

func (q *Queries) GetLLMProvider(ctx context.Context, id int64) (LlmProvider, error) {
	row := q.db.QueryRowContext(ctx, getLLMProvider, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLLMModel = `-- name: InsertLLMModel :exec
INSERT INTO llm_models (provider_id, name, is_default)
VALUES (?, ?, ?)
`

type InsertLLMModelParams struct {
	ProviderID int64
	Name       string
	IsDefault  int64
}

func (q *Queries) InsertLLMModel(ctx context.Context, arg InsertLLMModelParams) error {
	_, err := q.db.ExecContext(ctx, insertLLMModel, arg.ProviderID, arg.Name, arg.IsDefault)
	return err
}

const listLLMModelsByProvider = `-- name: ListLLMModelsByProvider :many
SELECT id, provider_id, name, is_default
FROM llm_models
WHERE provider_id = ?
ORDER BY id
`

func (q *Queries) ListLLMModelsByProvider(ctx context.Context, providerID int64) ([]LlmModel, error) {
	rows, err := q.db.QueryContext(ctx, listLLMModelsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmModel
	for rows.Next() {
		var i LlmModel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMProvidersByUser = `-- name: ListLLMProvidersByUser :many
SELECT id, user_id, name, provider, base_url, api_key, is_default, created_at, updated_at
FROM llm_providers
WHERE user_id = ?
ORDER BY id
`

func (q *Queries) ListLLMProvidersByUser(ctx context.Context, userID int64) ([]LlmProvider, error) {
	rows, err := q.db.QueryContext(ctx, listLLMProvidersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmProvider
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Provider,
			&i.BaseUrl,
			&i.ApiKey,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLLMProvider = `-- name: UpdateLLMProvider :one
UPDATE llm_providers
SET name = ?, provider = ?, base_url = ?, api_key = ?, is_default = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, user_id, name, provider, base_url, api_key, is_default, created_at, updated_at
`

type UpdateLLMProviderParams struct {
	Name      string
	Provider  string
	BaseUrl   string
	ApiKey    string
	IsDefault int64
	ID        int64
}

func (q *Queries) UpdateLLMProvider(ctx context.Context, arg UpdateLLMProviderParams) (LlmProvider, error) {
	row := q.db.QueryRowContext(ctx, updateLLMProvider,
		arg.Name,
		arg.Provider,
		arg.BaseUrl,
		arg.ApiKey,
		arg.IsDefault,
		arg.ID,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
