// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_provider.sql

package db

import (
	"context"
)

const getLLMProvider = `-- name: GetLLMProvider :one
SELECT id, provider, base_url, api_key, model, updated_at
FROM llm_providers
WHERE id = 1
`

func (q *Queries) GetLLMProvider(ctx context.Context) (LlmProvider, error) {
	row := q.db.QueryRowContext(ctx, getLLMProvider)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Model,
		&i.UpdatedAt,
	)
	return i, err
}

const setLLMModel = `-- name: SetLLMModel :one
UPDATE llm_providers
SET model = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = 1
RETURNING id, provider, base_url, api_key, model, updated_at
`

func (q *Queries) SetLLMModel(ctx context.Context, model string) (LlmProvider, error) {
	row := q.db.QueryRowContext(ctx, setLLMModel, model)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Model,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLLMProvider = `-- name: UpsertLLMProvider :one
INSERT INTO llm_providers (id, provider, base_url, api_key, model)
VALUES (1, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
	provider = excluded.provider,
	base_url = excluded.base_url,
	api_key = excluded.api_key,
	model = excluded.model,
	updated_at = CURRENT_TIMESTAMP
RETURNING id, provider, base_url, api_key, model, updated_at
`

type UpsertLLMProviderParams struct {
	Provider string
	BaseUrl  string
	ApiKey   string
	Model    string
}

func (q *Queries) UpsertLLMProvider(ctx context.Context, arg UpsertLLMProviderParams) (LlmProvider, error) {
	row := q.db.QueryRowContext(ctx, upsertLLMProvider,
		arg.Provider,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Model,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Model,
		&i.UpdatedAt,
	)
	return i, err
}
