// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package db

import (
	"context"
)

const appendMessage = `-- name: AppendMessage :one
INSERT INTO messages (session_id, role, content)
VALUES (?, ?, ?)
RETURNING id, session_id, role, content, created_at
`

type AppendMessageParams struct {
	SessionID int64
	Role      string
	Content   string
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, appendMessage, arg.SessionID, arg.Role, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, session_id, role, content, created_at
FROM (
	SELECT id, session_id, role, content, created_at
	FROM messages
	WHERE session_id = ?
	ORDER BY id DESC
	LIMIT ? OFFSET ?
)
ORDER BY id ASC
`

type ListMessagesParams struct {
	SessionID int64
	Limit     int64
	Offset    int64
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
