// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AuthSession struct {
	ID         int64
	Token      string
	UserID     int64
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastAccess time.Time
	Metadata   sql.NullString
}

type AuthUser struct {
	ID              int64
	Email           string
	Password        sql.NullString
	EmailVerifiedAt sql.NullTime
	FirstName       string
	LastName        string
	Role            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AuthVerification struct {
	ID        int64
	Subject   string
	Value     string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Job struct {
	ID         int64
	UserID     int64
	SessionID  sql.NullInt64
	Schedule   string
	Prompt     string
	Enabled    int64
	LastRunAt  sql.NullTime
	LastStatus string
	NextRunAt  sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Message struct {
	ID        int64
	SessionID int64
	Role      string
	Content   string
	CreatedAt time.Time
}

type Session struct {
	ID        int64
	UserID    int64
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ToolCall struct {
	ID        int64
	MessageID int64
	CallID    string
	Name      string
	Arguments string
	Result    string
	Status    string
	CreatedAt time.Time
}
