// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package db

import (
	"context"
	"database/sql"
)

const deleteUserPermissions = `-- name: DeleteUserPermissions :exec
DELETE FROM user_permissions
WHERE user_id = ?
`

func (q *Queries) DeleteUserPermissions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserPermissions, userID)
	return err
}

const getUserPermissions = `-- name: GetUserPermissions :one
SELECT user_id, default_verdict, rules, updated_at
FROM user_permissions
WHERE user_id = ?
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID int64) (UserPermission, error) {
	row := q.db.QueryRowContext(ctx, getUserPermissions, userID)
	var i UserPermission
	err := row.Scan(
		&i.UserID,
		&i.DefaultVerdict,
		&i.Rules,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPermissions = `-- name: UpsertUserPermissions :one
INSERT INTO user_permissions (user_id, default_verdict, rules, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (user_id) DO UPDATE SET
	default_verdict = excluded.default_verdict,
	rules = excluded.rules,
	updated_at = CURRENT_TIMESTAMP
RETURNING user_id, default_verdict, rules, updated_at
`

type UpsertUserPermissionsParams struct {
	UserID         int64
	DefaultVerdict sql.NullString
	Rules          string
}

func (q *Queries) UpsertUserPermissions(ctx context.Context, arg UpsertUserPermissionsParams) (UserPermission, error) {
	row := q.db.QueryRowContext(ctx, upsertUserPermissions, arg.UserID, arg.DefaultVerdict, arg.Rules)
	var i UserPermission
	err := row.Scan(
		&i.UserID,
		&i.DefaultVerdict,
		&i.Rules,
		&i.UpdatedAt,
	)
	return i, err
}
