// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pref.sql

package db

import (
	"context"
	"database/sql"
)

const deleteUserLLMPrefs = `-- name: DeleteUserLLMPrefs :exec
DELETE FROM user_llm_prefs
WHERE user_id = ?
`

func (q *Queries) DeleteUserLLMPrefs(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserLLMPrefs, userID)
	return err
}

const getUserLLMPrefs = `-- name: GetUserLLMPrefs :one
SELECT user_id, provider_id, model, updated_at
FROM user_llm_prefs
WHERE user_id = ?
`

func (q *Queries) GetUserLLMPrefs(ctx context.Context, userID int64) (UserLlmPref, error) {
	row := q.db.QueryRowContext(ctx, getUserLLMPrefs, userID)
	var i UserLlmPref
	err := row.Scan(
		&i.UserID,
		&i.ProviderID,
		&i.Model,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserLLMPrefs = `-- name: UpsertUserLLMPrefs :one
INSERT INTO user_llm_prefs (user_id, provider_id, model, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (user_id) DO UPDATE SET
	provider_id = excluded.provider_id,
	model = excluded.model,
	updated_at = CURRENT_TIMESTAMP
RETURNING user_id, provider_id, model, updated_at
`

type UpsertUserLLMPrefsParams struct {
	UserID     int64
	ProviderID sql.NullInt64
	Model      string
}

func (q *Queries) UpsertUserLLMPrefs(ctx context.Context, arg UpsertUserLLMPrefsParams) (UserLlmPref, error) {
	row := q.db.QueryRowContext(ctx, upsertUserLLMPrefs, arg.UserID, arg.ProviderID, arg.Model)
	var i UserLlmPref
	err := row.Scan(
		&i.UserID,
		&i.ProviderID,
		&i.Model,
		&i.UpdatedAt,
	)
	return i, err
}
