// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setting.sql

package db

import (
	"context"
)

const deleteUserSettings = `-- name: DeleteUserSettings :exec
DELETE FROM user_settings
WHERE user_id = ?
`

func (q *Queries) DeleteUserSettings(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSettings, userID)
	return err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, llm_provider, llm_base_url, llm_api_key, llm_model, updated_at
FROM user_settings
WHERE user_id = ?
`

func (q *Queries) GetUserSettings(ctx context.Context, userID int64) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.LlmProvider,
		&i.LlmBaseUrl,
		&i.LlmApiKey,
		&i.LlmModel,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :one
INSERT INTO user_settings (user_id, llm_provider, llm_base_url, llm_api_key, llm_model, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (user_id) DO UPDATE SET
	llm_provider = excluded.llm_provider,
	llm_base_url = excluded.llm_base_url,
	llm_api_key = excluded.llm_api_key,
	llm_model = excluded.llm_model,
	updated_at = CURRENT_TIMESTAMP
RETURNING user_id, llm_provider, llm_base_url, llm_api_key, llm_model, updated_at
`

type UpsertUserSettingsParams struct {
	UserID      int64
	LlmProvider string
	LlmBaseUrl  string
	LlmApiKey   string
	LlmModel    string
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertUserSettings,
		arg.UserID,
		arg.LlmProvider,
		arg.LlmBaseUrl,
		arg.LlmApiKey,
		arg.LlmModel,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.LlmProvider,
		&i.LlmBaseUrl,
		&i.LlmApiKey,
		&i.LlmModel,
		&i.UpdatedAt,
	)
	return i, err
}
