// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, permission_default, permission_rules, updated_at, instructions
FROM settings
WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.PermissionDefault,
		&i.PermissionRules,
		&i.UpdatedAt,
		&i.Instructions,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :one
INSERT INTO settings (id, permission_default, permission_rules, instructions)
VALUES (1, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
	permission_default = excluded.permission_default,
	permission_rules = excluded.permission_rules,
	instructions = excluded.instructions,
	updated_at = CURRENT_TIMESTAMP
RETURNING id, permission_default, permission_rules, updated_at, instructions
`

type UpsertSettingsParams struct {
	PermissionDefault string
	PermissionRules   string
	Instructions      string
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, upsertSettings, arg.PermissionDefault, arg.PermissionRules, arg.Instructions)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.PermissionDefault,
		&i.PermissionRules,
		&i.UpdatedAt,
		&i.Instructions,
	)
	return i, err
}
