// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tool_call.sql

package db

import (
	"context"
)

const insertToolCall = `-- name: InsertToolCall :one
INSERT INTO tool_calls (message_id, call_id, name, arguments, status)
VALUES (?, ?, ?, ?, ?)
RETURNING id, message_id, call_id, name, arguments, result, status, created_at
`

type InsertToolCallParams struct {
	MessageID int64
	CallID    string
	Name      string
	Arguments string
	Status    string
}

func (q *Queries) InsertToolCall(ctx context.Context, arg InsertToolCallParams) (ToolCall, error) {
	row := q.db.QueryRowContext(ctx, insertToolCall,
		arg.MessageID,
		arg.CallID,
		arg.Name,
		arg.Arguments,
		arg.Status,
	)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.CallID,
		&i.Name,
		&i.Arguments,
		&i.Result,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listToolCallsBySession = `-- name: ListToolCallsBySession :many
SELECT tc.id, tc.message_id, tc.call_id, tc.name, tc.arguments, tc.result, tc.status, tc.created_at
FROM tool_calls tc
JOIN messages m ON m.id = tc.message_id
WHERE m.session_id = ?
ORDER BY tc.message_id, tc.id
`

func (q *Queries) ListToolCallsBySession(ctx context.Context, sessionID int64) ([]ToolCall, error) {
	rows, err := q.db.QueryContext(ctx, listToolCallsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolCall
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.CallID,
			&i.Name,
			&i.Arguments,
			&i.Result,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateToolCallResult = `-- name: UpdateToolCallResult :exec
UPDATE tool_calls
SET result = ?, status = ?
WHERE id = ?
`

type UpdateToolCallResultParams struct {
	Result string
	Status string
	ID     int64
}

func (q *Queries) UpdateToolCallResult(ctx context.Context, arg UpdateToolCallResultParams) error {
	_, err := q.db.ExecContext(ctx, updateToolCallResult, arg.Result, arg.Status, arg.ID)
	return err
}
