#!/usr/bin/env bash
# Recount oracle's source-line statistics for docs/code_stats.md.
#
# Run from the repo root:  ./scripts/stats.sh
# This must be run in a git work tree. It counts git-tracked files only.
set -euo pipefail

# Sums the line counts of every tracked file matched by the given transform.
# git ls-files -z + grep -z lets us pass a filter. xargs wc then awk sums the
# per-file rows and skips wc's aggregate "total" row so nothing is double
# counted (and single-file results, printed as "<n> <file>", still count).
sum() { # $@: ls-files pathspecs. stdin may add an extra grep filter via pipe
  xargs -0 wc -l | awk '!/ total$/{s+=$1} END{print s}'
}

wc_tracked() { # $@ : git ls-files pathspecs (no filter)
  git ls-files -z -- "$@" | sum
}

go_all=$(wc_tracked 'apps/api/**/*.go')
go_src=$(git ls-files -z -- 'apps/api/**/*.go' | grep -z -v -E '_test\.go$|/internal/store/db/' | sum)
go_test=$(git ls-files -z -- 'apps/api/**/*_test.go' | sum)
go_gen=$(wc_tracked 'apps/api/internal/store/db/*.go')

web_all=$(git ls-files -z -- 'apps/web/**' | grep -z -E '\.(ts|svelte|css|js)$' | sum)
web_svelte=$(git ls-files -z -- 'apps/web/**' | grep -z -E '\.svelte$' | sum)
web_tsjs=$(git ls-files -z -- 'apps/web/**' | grep -z -E '\.(ts|js)$' | sum)
web_css=$(git ls-files -z -- 'apps/web/**' | grep -z -E '\.css$' | sum)

sql_mig=$(git ls-files -z -- 'apps/api/migrations/*.sql' | sum)
sql_qry=$(git ls-files -z -- 'apps/api/db/**/*.sql' | sum)

other=$(git ls-files -z | grep -z -v -E '.*\.go$' \
  | grep -z -E '\.(lock|sum|json|md|mod|yaml|yml|toml|svg|txt|html|css)$' \
  | sum)

total=$(git ls-files -z | sum)

echo "go_total       $go_all"
echo "go_source      $go_src   (non-test, excludes generated db/)"
echo "go_test        $go_test"
echo "go_generated   $go_gen   (sqlc db/, regenerated by make sqlc)"
echo "web_total      $web_all"
echo "web_svelte     $web_svelte"
echo "web_tsjs       $web_tsjs"
echo "web_css        $web_css"
echo "sql_migrations $sql_mig"
echo "sql_queries    $sql_qry"
echo "other          $other    (locks/config/docs/static, non-go non-web)"
echo "repo_total     $total"
